/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HfModelsRouteImport } from './routes/hf-models'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewVisualizeRouteImport } from './routes/new.visualize'
import { Route as NewVariablesRouteImport } from './routes/new.variables'
import { Route as NewUploadRouteImport } from './routes/new.upload'
import { Route as NewTrainRouteImport } from './routes/new.train'
import { Route as NewSplitRouteImport } from './routes/new.split'
import { Route as NewReportRouteImport } from './routes/new.report'
import { Route as NewPreprocessingRouteImport } from './routes/new.preprocessing'
import { Route as NewPredictRouteImport } from './routes/new.predict'
import { Route as NewModelRouteImport } from './routes/new.model'
import { Route as NewMetricsRouteImport } from './routes/new.metrics'
import { Route as NewExplainRouteImport } from './routes/new.explain'
import { Route as ModelsModelIdRouteImport } from './routes/models.$modelId'
import { Route as ClusterVisualizeRouteImport } from './routes/cluster.visualize'
import { Route as ClusterVariablesRouteImport } from './routes/cluster.variables'
import { Route as ClusterUploadRouteImport } from './routes/cluster.upload'
import { Route as ClusterTrainRouteImport } from './routes/cluster.train'
import { Route as ClusterReportRouteImport } from './routes/cluster.report'
import { Route as ClusterModelRouteImport } from './routes/cluster.model'
import { Route as ClusterExplainRouteImport } from './routes/cluster.explain'
import { Route as ClusterAnalysisRouteImport } from './routes/cluster.analysis'
import { Route as ClassifyVisualizeRouteImport } from './routes/classify.visualize'
import { Route as ClassifyVariablesRouteImport } from './routes/classify.variables'
import { Route as ClassifyUploadRouteImport } from './routes/classify.upload'
import { Route as ClassifyTrainRouteImport } from './routes/classify.train'
import { Route as ClassifySplitRouteImport } from './routes/classify.split'
import { Route as ClassifyReportRouteImport } from './routes/classify.report'
import { Route as ClassifyPreprocessingRouteImport } from './routes/classify.preprocessing'
import { Route as ClassifyPredictRouteImport } from './routes/classify.predict'
import { Route as ClassifyModelRouteImport } from './routes/classify.model'
import { Route as ClassifyMetricsRouteImport } from './routes/classify.metrics'
import { Route as ClassifyExplainRouteImport } from './routes/classify.explain'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HfModelsRoute = HfModelsRouteImport.update({
  id: '/hf-models',
  path: '/hf-models',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewVisualizeRoute = NewVisualizeRouteImport.update({
  id: '/new/visualize',
  path: '/new/visualize',
  getParentRoute: () => rootRouteImport,
} as any)
const NewVariablesRoute = NewVariablesRouteImport.update({
  id: '/new/variables',
  path: '/new/variables',
  getParentRoute: () => rootRouteImport,
} as any)
const NewUploadRoute = NewUploadRouteImport.update({
  id: '/new/upload',
  path: '/new/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const NewTrainRoute = NewTrainRouteImport.update({
  id: '/new/train',
  path: '/new/train',
  getParentRoute: () => rootRouteImport,
} as any)
const NewSplitRoute = NewSplitRouteImport.update({
  id: '/new/split',
  path: '/new/split',
  getParentRoute: () => rootRouteImport,
} as any)
const NewReportRoute = NewReportRouteImport.update({
  id: '/new/report',
  path: '/new/report',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPreprocessingRoute = NewPreprocessingRouteImport.update({
  id: '/new/preprocessing',
  path: '/new/preprocessing',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPredictRoute = NewPredictRouteImport.update({
  id: '/new/predict',
  path: '/new/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const NewModelRoute = NewModelRouteImport.update({
  id: '/new/model',
  path: '/new/model',
  getParentRoute: () => rootRouteImport,
} as any)
const NewMetricsRoute = NewMetricsRouteImport.update({
  id: '/new/metrics',
  path: '/new/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const NewExplainRoute = NewExplainRouteImport.update({
  id: '/new/explain',
  path: '/new/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsModelIdRoute = ModelsModelIdRouteImport.update({
  id: '/models/$modelId',
  path: '/models/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterVisualizeRoute = ClusterVisualizeRouteImport.update({
  id: '/cluster/visualize',
  path: '/cluster/visualize',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterVariablesRoute = ClusterVariablesRouteImport.update({
  id: '/cluster/variables',
  path: '/cluster/variables',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterUploadRoute = ClusterUploadRouteImport.update({
  id: '/cluster/upload',
  path: '/cluster/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterTrainRoute = ClusterTrainRouteImport.update({
  id: '/cluster/train',
  path: '/cluster/train',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterReportRoute = ClusterReportRouteImport.update({
  id: '/cluster/report',
  path: '/cluster/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterModelRoute = ClusterModelRouteImport.update({
  id: '/cluster/model',
  path: '/cluster/model',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterExplainRoute = ClusterExplainRouteImport.update({
  id: '/cluster/explain',
  path: '/cluster/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterAnalysisRoute = ClusterAnalysisRouteImport.update({
  id: '/cluster/analysis',
  path: '/cluster/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifyVisualizeRoute = ClassifyVisualizeRouteImport.update({
  id: '/classify/visualize',
  path: '/classify/visualize',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifyVariablesRoute = ClassifyVariablesRouteImport.update({
  id: '/classify/variables',
  path: '/classify/variables',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifyUploadRoute = ClassifyUploadRouteImport.update({
  id: '/classify/upload',
  path: '/classify/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifyTrainRoute = ClassifyTrainRouteImport.update({
  id: '/classify/train',
  path: '/classify/train',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifySplitRoute = ClassifySplitRouteImport.update({
  id: '/classify/split',
  path: '/classify/split',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifyReportRoute = ClassifyReportRouteImport.update({
  id: '/classify/report',
  path: '/classify/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifyPreprocessingRoute = ClassifyPreprocessingRouteImport.update({
  id: '/classify/preprocessing',
  path: '/classify/preprocessing',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifyPredictRoute = ClassifyPredictRouteImport.update({
  id: '/classify/predict',
  path: '/classify/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifyModelRoute = ClassifyModelRouteImport.update({
  id: '/classify/model',
  path: '/classify/model',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifyMetricsRoute = ClassifyMetricsRouteImport.update({
  id: '/classify/metrics',
  path: '/classify/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifyExplainRoute = ClassifyExplainRouteImport.update({
  id: '/classify/explain',
  path: '/classify/explain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/compare': typeof CompareRoute
  '/data-sources': typeof DataSourcesRoute
  '/hf-models': typeof HfModelsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/classify/explain': typeof ClassifyExplainRoute
  '/classify/metrics': typeof ClassifyMetricsRoute
  '/classify/model': typeof ClassifyModelRoute
  '/classify/predict': typeof ClassifyPredictRoute
  '/classify/preprocessing': typeof ClassifyPreprocessingRoute
  '/classify/report': typeof ClassifyReportRoute
  '/classify/split': typeof ClassifySplitRoute
  '/classify/train': typeof ClassifyTrainRoute
  '/classify/upload': typeof ClassifyUploadRoute
  '/classify/variables': typeof ClassifyVariablesRoute
  '/classify/visualize': typeof ClassifyVisualizeRoute
  '/cluster/analysis': typeof ClusterAnalysisRoute
  '/cluster/explain': typeof ClusterExplainRoute
  '/cluster/model': typeof ClusterModelRoute
  '/cluster/report': typeof ClusterReportRoute
  '/cluster/train': typeof ClusterTrainRoute
  '/cluster/upload': typeof ClusterUploadRoute
  '/cluster/variables': typeof ClusterVariablesRoute
  '/cluster/visualize': typeof ClusterVisualizeRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/new/explain': typeof NewExplainRoute
  '/new/metrics': typeof NewMetricsRoute
  '/new/model': typeof NewModelRoute
  '/new/predict': typeof NewPredictRoute
  '/new/preprocessing': typeof NewPreprocessingRoute
  '/new/report': typeof NewReportRoute
  '/new/split': typeof NewSplitRoute
  '/new/train': typeof NewTrainRoute
  '/new/upload': typeof NewUploadRoute
  '/new/variables': typeof NewVariablesRoute
  '/new/visualize': typeof NewVisualizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/compare': typeof CompareRoute
  '/data-sources': typeof DataSourcesRoute
  '/hf-models': typeof HfModelsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/classify/explain': typeof ClassifyExplainRoute
  '/classify/metrics': typeof ClassifyMetricsRoute
  '/classify/model': typeof ClassifyModelRoute
  '/classify/predict': typeof ClassifyPredictRoute
  '/classify/preprocessing': typeof ClassifyPreprocessingRoute
  '/classify/report': typeof ClassifyReportRoute
  '/classify/split': typeof ClassifySplitRoute
  '/classify/train': typeof ClassifyTrainRoute
  '/classify/upload': typeof ClassifyUploadRoute
  '/classify/variables': typeof ClassifyVariablesRoute
  '/classify/visualize': typeof ClassifyVisualizeRoute
  '/cluster/analysis': typeof ClusterAnalysisRoute
  '/cluster/explain': typeof ClusterExplainRoute
  '/cluster/model': typeof ClusterModelRoute
  '/cluster/report': typeof ClusterReportRoute
  '/cluster/train': typeof ClusterTrainRoute
  '/cluster/upload': typeof ClusterUploadRoute
  '/cluster/variables': typeof ClusterVariablesRoute
  '/cluster/visualize': typeof ClusterVisualizeRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/new/explain': typeof NewExplainRoute
  '/new/metrics': typeof NewMetricsRoute
  '/new/model': typeof NewModelRoute
  '/new/predict': typeof NewPredictRoute
  '/new/preprocessing': typeof NewPreprocessingRoute
  '/new/report': typeof NewReportRoute
  '/new/split': typeof NewSplitRoute
  '/new/train': typeof NewTrainRoute
  '/new/upload': typeof NewUploadRoute
  '/new/variables': typeof NewVariablesRoute
  '/new/visualize': typeof NewVisualizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/compare': typeof CompareRoute
  '/data-sources': typeof DataSourcesRoute
  '/hf-models': typeof HfModelsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/classify/explain': typeof ClassifyExplainRoute
  '/classify/metrics': typeof ClassifyMetricsRoute
  '/classify/model': typeof ClassifyModelRoute
  '/classify/predict': typeof ClassifyPredictRoute
  '/classify/preprocessing': typeof ClassifyPreprocessingRoute
  '/classify/report': typeof ClassifyReportRoute
  '/classify/split': typeof ClassifySplitRoute
  '/classify/train': typeof ClassifyTrainRoute
  '/classify/upload': typeof ClassifyUploadRoute
  '/classify/variables': typeof ClassifyVariablesRoute
  '/classify/visualize': typeof ClassifyVisualizeRoute
  '/cluster/analysis': typeof ClusterAnalysisRoute
  '/cluster/explain': typeof ClusterExplainRoute
  '/cluster/model': typeof ClusterModelRoute
  '/cluster/report': typeof ClusterReportRoute
  '/cluster/train': typeof ClusterTrainRoute
  '/cluster/upload': typeof ClusterUploadRoute
  '/cluster/variables': typeof ClusterVariablesRoute
  '/cluster/visualize': typeof ClusterVisualizeRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/new/explain': typeof NewExplainRoute
  '/new/metrics': typeof NewMetricsRoute
  '/new/model': typeof NewModelRoute
  '/new/predict': typeof NewPredictRoute
  '/new/preprocessing': typeof NewPreprocessingRoute
  '/new/report': typeof NewReportRoute
  '/new/split': typeof NewSplitRoute
  '/new/train': typeof NewTrainRoute
  '/new/upload': typeof NewUploadRoute
  '/new/variables': typeof NewVariablesRoute
  '/new/visualize': typeof NewVisualizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/compare'
    | '/data-sources'
    | '/hf-models'
    | '/history'
    | '/login'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/classify/explain'
    | '/classify/metrics'
    | '/classify/model'
    | '/classify/predict'
    | '/classify/preprocessing'
    | '/classify/report'
    | '/classify/split'
    | '/classify/train'
    | '/classify/upload'
    | '/classify/variables'
    | '/classify/visualize'
    | '/cluster/analysis'
    | '/cluster/explain'
    | '/cluster/model'
    | '/cluster/report'
    | '/cluster/train'
    | '/cluster/upload'
    | '/cluster/variables'
    | '/cluster/visualize'
    | '/models/$modelId'
    | '/new/explain'
    | '/new/metrics'
    | '/new/model'
    | '/new/predict'
    | '/new/preprocessing'
    | '/new/report'
    | '/new/split'
    | '/new/train'
    | '/new/upload'
    | '/new/variables'
    | '/new/visualize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/compare'
    | '/data-sources'
    | '/hf-models'
    | '/history'
    | '/login'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/classify/explain'
    | '/classify/metrics'
    | '/classify/model'
    | '/classify/predict'
    | '/classify/preprocessing'
    | '/classify/report'
    | '/classify/split'
    | '/classify/train'
    | '/classify/upload'
    | '/classify/variables'
    | '/classify/visualize'
    | '/cluster/analysis'
    | '/cluster/explain'
    | '/cluster/model'
    | '/cluster/report'
    | '/cluster/train'
    | '/cluster/upload'
    | '/cluster/variables'
    | '/cluster/visualize'
    | '/models/$modelId'
    | '/new/explain'
    | '/new/metrics'
    | '/new/model'
    | '/new/predict'
    | '/new/preprocessing'
    | '/new/report'
    | '/new/split'
    | '/new/train'
    | '/new/upload'
    | '/new/variables'
    | '/new/visualize'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/compare'
    | '/data-sources'
    | '/hf-models'
    | '/history'
    | '/login'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/classify/explain'
    | '/classify/metrics'
    | '/classify/model'
    | '/classify/predict'
    | '/classify/preprocessing'
    | '/classify/report'
    | '/classify/split'
    | '/classify/train'
    | '/classify/upload'
    | '/classify/variables'
    | '/classify/visualize'
    | '/cluster/analysis'
    | '/cluster/explain'
    | '/cluster/model'
    | '/cluster/report'
    | '/cluster/train'
    | '/cluster/upload'
    | '/cluster/variables'
    | '/cluster/visualize'
    | '/models/$modelId'
    | '/new/explain'
    | '/new/metrics'
    | '/new/model'
    | '/new/predict'
    | '/new/preprocessing'
    | '/new/report'
    | '/new/split'
    | '/new/train'
    | '/new/upload'
    | '/new/variables'
    | '/new/visualize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  CompareRoute: typeof CompareRoute
  DataSourcesRoute: typeof DataSourcesRoute
  HfModelsRoute: typeof HfModelsRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  ClassifyExplainRoute: typeof ClassifyExplainRoute
  ClassifyMetricsRoute: typeof ClassifyMetricsRoute
  ClassifyModelRoute: typeof ClassifyModelRoute
  ClassifyPredictRoute: typeof ClassifyPredictRoute
  ClassifyPreprocessingRoute: typeof ClassifyPreprocessingRoute
  ClassifyReportRoute: typeof ClassifyReportRoute
  ClassifySplitRoute: typeof ClassifySplitRoute
  ClassifyTrainRoute: typeof ClassifyTrainRoute
  ClassifyUploadRoute: typeof ClassifyUploadRoute
  ClassifyVariablesRoute: typeof ClassifyVariablesRoute
  ClassifyVisualizeRoute: typeof ClassifyVisualizeRoute
  ClusterAnalysisRoute: typeof ClusterAnalysisRoute
  ClusterExplainRoute: typeof ClusterExplainRoute
  ClusterModelRoute: typeof ClusterModelRoute
  ClusterReportRoute: typeof ClusterReportRoute
  ClusterTrainRoute: typeof ClusterTrainRoute
  ClusterUploadRoute: typeof ClusterUploadRoute
  ClusterVariablesRoute: typeof ClusterVariablesRoute
  ClusterVisualizeRoute: typeof ClusterVisualizeRoute
  ModelsModelIdRoute: typeof ModelsModelIdRoute
  NewExplainRoute: typeof NewExplainRoute
  NewMetricsRoute: typeof NewMetricsRoute
  NewModelRoute: typeof NewModelRoute
  NewPredictRoute: typeof NewPredictRoute
  NewPreprocessingRoute: typeof NewPreprocessingRoute
  NewReportRoute: typeof NewReportRoute
  NewSplitRoute: typeof NewSplitRoute
  NewTrainRoute: typeof NewTrainRoute
  NewUploadRoute: typeof NewUploadRoute
  NewVariablesRoute: typeof NewVariablesRoute
  NewVisualizeRoute: typeof NewVisualizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hf-models': {
      id: '/hf-models'
      path: '/hf-models'
      fullPath: '/hf-models'
      preLoaderRoute: typeof HfModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/visualize': {
      id: '/new/visualize'
      path: '/new/visualize'
      fullPath: '/new/visualize'
      preLoaderRoute: typeof NewVisualizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/variables': {
      id: '/new/variables'
      path: '/new/variables'
      fullPath: '/new/variables'
      preLoaderRoute: typeof NewVariablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/upload': {
      id: '/new/upload'
      path: '/new/upload'
      fullPath: '/new/upload'
      preLoaderRoute: typeof NewUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/train': {
      id: '/new/train'
      path: '/new/train'
      fullPath: '/new/train'
      preLoaderRoute: typeof NewTrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/split': {
      id: '/new/split'
      path: '/new/split'
      fullPath: '/new/split'
      preLoaderRoute: typeof NewSplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/report': {
      id: '/new/report'
      path: '/new/report'
      fullPath: '/new/report'
      preLoaderRoute: typeof NewReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/preprocessing': {
      id: '/new/preprocessing'
      path: '/new/preprocessing'
      fullPath: '/new/preprocessing'
      preLoaderRoute: typeof NewPreprocessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/predict': {
      id: '/new/predict'
      path: '/new/predict'
      fullPath: '/new/predict'
      preLoaderRoute: typeof NewPredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/model': {
      id: '/new/model'
      path: '/new/model'
      fullPath: '/new/model'
      preLoaderRoute: typeof NewModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/metrics': {
      id: '/new/metrics'
      path: '/new/metrics'
      fullPath: '/new/metrics'
      preLoaderRoute: typeof NewMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/explain': {
      id: '/new/explain'
      path: '/new/explain'
      fullPath: '/new/explain'
      preLoaderRoute: typeof NewExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$modelId': {
      id: '/models/$modelId'
      path: '/models/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof ModelsModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster/visualize': {
      id: '/cluster/visualize'
      path: '/cluster/visualize'
      fullPath: '/cluster/visualize'
      preLoaderRoute: typeof ClusterVisualizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster/variables': {
      id: '/cluster/variables'
      path: '/cluster/variables'
      fullPath: '/cluster/variables'
      preLoaderRoute: typeof ClusterVariablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster/upload': {
      id: '/cluster/upload'
      path: '/cluster/upload'
      fullPath: '/cluster/upload'
      preLoaderRoute: typeof ClusterUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster/train': {
      id: '/cluster/train'
      path: '/cluster/train'
      fullPath: '/cluster/train'
      preLoaderRoute: typeof ClusterTrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster/report': {
      id: '/cluster/report'
      path: '/cluster/report'
      fullPath: '/cluster/report'
      preLoaderRoute: typeof ClusterReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster/model': {
      id: '/cluster/model'
      path: '/cluster/model'
      fullPath: '/cluster/model'
      preLoaderRoute: typeof ClusterModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster/explain': {
      id: '/cluster/explain'
      path: '/cluster/explain'
      fullPath: '/cluster/explain'
      preLoaderRoute: typeof ClusterExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster/analysis': {
      id: '/cluster/analysis'
      path: '/cluster/analysis'
      fullPath: '/cluster/analysis'
      preLoaderRoute: typeof ClusterAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classify/visualize': {
      id: '/classify/visualize'
      path: '/classify/visualize'
      fullPath: '/classify/visualize'
      preLoaderRoute: typeof ClassifyVisualizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classify/variables': {
      id: '/classify/variables'
      path: '/classify/variables'
      fullPath: '/classify/variables'
      preLoaderRoute: typeof ClassifyVariablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classify/upload': {
      id: '/classify/upload'
      path: '/classify/upload'
      fullPath: '/classify/upload'
      preLoaderRoute: typeof ClassifyUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classify/train': {
      id: '/classify/train'
      path: '/classify/train'
      fullPath: '/classify/train'
      preLoaderRoute: typeof ClassifyTrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classify/split': {
      id: '/classify/split'
      path: '/classify/split'
      fullPath: '/classify/split'
      preLoaderRoute: typeof ClassifySplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classify/report': {
      id: '/classify/report'
      path: '/classify/report'
      fullPath: '/classify/report'
      preLoaderRoute: typeof ClassifyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classify/preprocessing': {
      id: '/classify/preprocessing'
      path: '/classify/preprocessing'
      fullPath: '/classify/preprocessing'
      preLoaderRoute: typeof ClassifyPreprocessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classify/predict': {
      id: '/classify/predict'
      path: '/classify/predict'
      fullPath: '/classify/predict'
      preLoaderRoute: typeof ClassifyPredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classify/model': {
      id: '/classify/model'
      path: '/classify/model'
      fullPath: '/classify/model'
      preLoaderRoute: typeof ClassifyModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classify/metrics': {
      id: '/classify/metrics'
      path: '/classify/metrics'
      fullPath: '/classify/metrics'
      preLoaderRoute: typeof ClassifyMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classify/explain': {
      id: '/classify/explain'
      path: '/classify/explain'
      fullPath: '/classify/explain'
      preLoaderRoute: typeof ClassifyExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  CompareRoute: CompareRoute,
  DataSourcesRoute: DataSourcesRoute,
  HfModelsRoute: HfModelsRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  ClassifyExplainRoute: ClassifyExplainRoute,
  ClassifyMetricsRoute: ClassifyMetricsRoute,
  ClassifyModelRoute: ClassifyModelRoute,
  ClassifyPredictRoute: ClassifyPredictRoute,
  ClassifyPreprocessingRoute: ClassifyPreprocessingRoute,
  ClassifyReportRoute: ClassifyReportRoute,
  ClassifySplitRoute: ClassifySplitRoute,
  ClassifyTrainRoute: ClassifyTrainRoute,
  ClassifyUploadRoute: ClassifyUploadRoute,
  ClassifyVariablesRoute: ClassifyVariablesRoute,
  ClassifyVisualizeRoute: ClassifyVisualizeRoute,
  ClusterAnalysisRoute: ClusterAnalysisRoute,
  ClusterExplainRoute: ClusterExplainRoute,
  ClusterModelRoute: ClusterModelRoute,
  ClusterReportRoute: ClusterReportRoute,
  ClusterTrainRoute: ClusterTrainRoute,
  ClusterUploadRoute: ClusterUploadRoute,
  ClusterVariablesRoute: ClusterVariablesRoute,
  ClusterVisualizeRoute: ClusterVisualizeRoute,
  ModelsModelIdRoute: ModelsModelIdRoute,
  NewExplainRoute: NewExplainRoute,
  NewMetricsRoute: NewMetricsRoute,
  NewModelRoute: NewModelRoute,
  NewPredictRoute: NewPredictRoute,
  NewPreprocessingRoute: NewPreprocessingRoute,
  NewReportRoute: NewReportRoute,
  NewSplitRoute: NewSplitRoute,
  NewTrainRoute: NewTrainRoute,
  NewUploadRoute: NewUploadRoute,
  NewVariablesRoute: NewVariablesRoute,
  NewVisualizeRoute: NewVisualizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
