/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewVisualizeRouteImport } from './routes/new.visualize'
import { Route as NewVariablesRouteImport } from './routes/new.variables'
import { Route as NewUploadRouteImport } from './routes/new.upload'
import { Route as NewTrainRouteImport } from './routes/new.train'
import { Route as NewSplitRouteImport } from './routes/new.split'
import { Route as NewReportRouteImport } from './routes/new.report'
import { Route as NewPreprocessingRouteImport } from './routes/new.preprocessing'
import { Route as NewPredictRouteImport } from './routes/new.predict'
import { Route as NewModelRouteImport } from './routes/new.model'
import { Route as NewMetricsRouteImport } from './routes/new.metrics'
import { Route as NewExplainRouteImport } from './routes/new.explain'
import { Route as ModelsModelIdRouteImport } from './routes/models.$modelId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewVisualizeRoute = NewVisualizeRouteImport.update({
  id: '/new/visualize',
  path: '/new/visualize',
  getParentRoute: () => rootRouteImport,
} as any)
const NewVariablesRoute = NewVariablesRouteImport.update({
  id: '/new/variables',
  path: '/new/variables',
  getParentRoute: () => rootRouteImport,
} as any)
const NewUploadRoute = NewUploadRouteImport.update({
  id: '/new/upload',
  path: '/new/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const NewTrainRoute = NewTrainRouteImport.update({
  id: '/new/train',
  path: '/new/train',
  getParentRoute: () => rootRouteImport,
} as any)
const NewSplitRoute = NewSplitRouteImport.update({
  id: '/new/split',
  path: '/new/split',
  getParentRoute: () => rootRouteImport,
} as any)
const NewReportRoute = NewReportRouteImport.update({
  id: '/new/report',
  path: '/new/report',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPreprocessingRoute = NewPreprocessingRouteImport.update({
  id: '/new/preprocessing',
  path: '/new/preprocessing',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPredictRoute = NewPredictRouteImport.update({
  id: '/new/predict',
  path: '/new/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const NewModelRoute = NewModelRouteImport.update({
  id: '/new/model',
  path: '/new/model',
  getParentRoute: () => rootRouteImport,
} as any)
const NewMetricsRoute = NewMetricsRouteImport.update({
  id: '/new/metrics',
  path: '/new/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const NewExplainRoute = NewExplainRouteImport.update({
  id: '/new/explain',
  path: '/new/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsModelIdRoute = ModelsModelIdRouteImport.update({
  id: '/models/$modelId',
  path: '/models/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/compare': typeof CompareRoute
  '/data-sources': typeof DataSourcesRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/new/explain': typeof NewExplainRoute
  '/new/metrics': typeof NewMetricsRoute
  '/new/model': typeof NewModelRoute
  '/new/predict': typeof NewPredictRoute
  '/new/preprocessing': typeof NewPreprocessingRoute
  '/new/report': typeof NewReportRoute
  '/new/split': typeof NewSplitRoute
  '/new/train': typeof NewTrainRoute
  '/new/upload': typeof NewUploadRoute
  '/new/variables': typeof NewVariablesRoute
  '/new/visualize': typeof NewVisualizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/compare': typeof CompareRoute
  '/data-sources': typeof DataSourcesRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/new/explain': typeof NewExplainRoute
  '/new/metrics': typeof NewMetricsRoute
  '/new/model': typeof NewModelRoute
  '/new/predict': typeof NewPredictRoute
  '/new/preprocessing': typeof NewPreprocessingRoute
  '/new/report': typeof NewReportRoute
  '/new/split': typeof NewSplitRoute
  '/new/train': typeof NewTrainRoute
  '/new/upload': typeof NewUploadRoute
  '/new/variables': typeof NewVariablesRoute
  '/new/visualize': typeof NewVisualizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/compare': typeof CompareRoute
  '/data-sources': typeof DataSourcesRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/new/explain': typeof NewExplainRoute
  '/new/metrics': typeof NewMetricsRoute
  '/new/model': typeof NewModelRoute
  '/new/predict': typeof NewPredictRoute
  '/new/preprocessing': typeof NewPreprocessingRoute
  '/new/report': typeof NewReportRoute
  '/new/split': typeof NewSplitRoute
  '/new/train': typeof NewTrainRoute
  '/new/upload': typeof NewUploadRoute
  '/new/variables': typeof NewVariablesRoute
  '/new/visualize': typeof NewVisualizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/compare'
    | '/data-sources'
    | '/history'
    | '/login'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/models/$modelId'
    | '/new/explain'
    | '/new/metrics'
    | '/new/model'
    | '/new/predict'
    | '/new/preprocessing'
    | '/new/report'
    | '/new/split'
    | '/new/train'
    | '/new/upload'
    | '/new/variables'
    | '/new/visualize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/compare'
    | '/data-sources'
    | '/history'
    | '/login'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/models/$modelId'
    | '/new/explain'
    | '/new/metrics'
    | '/new/model'
    | '/new/predict'
    | '/new/preprocessing'
    | '/new/report'
    | '/new/split'
    | '/new/train'
    | '/new/upload'
    | '/new/variables'
    | '/new/visualize'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/compare'
    | '/data-sources'
    | '/history'
    | '/login'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/models/$modelId'
    | '/new/explain'
    | '/new/metrics'
    | '/new/model'
    | '/new/predict'
    | '/new/preprocessing'
    | '/new/report'
    | '/new/split'
    | '/new/train'
    | '/new/upload'
    | '/new/variables'
    | '/new/visualize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  CompareRoute: typeof CompareRoute
  DataSourcesRoute: typeof DataSourcesRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  ModelsModelIdRoute: typeof ModelsModelIdRoute
  NewExplainRoute: typeof NewExplainRoute
  NewMetricsRoute: typeof NewMetricsRoute
  NewModelRoute: typeof NewModelRoute
  NewPredictRoute: typeof NewPredictRoute
  NewPreprocessingRoute: typeof NewPreprocessingRoute
  NewReportRoute: typeof NewReportRoute
  NewSplitRoute: typeof NewSplitRoute
  NewTrainRoute: typeof NewTrainRoute
  NewUploadRoute: typeof NewUploadRoute
  NewVariablesRoute: typeof NewVariablesRoute
  NewVisualizeRoute: typeof NewVisualizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/visualize': {
      id: '/new/visualize'
      path: '/new/visualize'
      fullPath: '/new/visualize'
      preLoaderRoute: typeof NewVisualizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/variables': {
      id: '/new/variables'
      path: '/new/variables'
      fullPath: '/new/variables'
      preLoaderRoute: typeof NewVariablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/upload': {
      id: '/new/upload'
      path: '/new/upload'
      fullPath: '/new/upload'
      preLoaderRoute: typeof NewUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/train': {
      id: '/new/train'
      path: '/new/train'
      fullPath: '/new/train'
      preLoaderRoute: typeof NewTrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/split': {
      id: '/new/split'
      path: '/new/split'
      fullPath: '/new/split'
      preLoaderRoute: typeof NewSplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/report': {
      id: '/new/report'
      path: '/new/report'
      fullPath: '/new/report'
      preLoaderRoute: typeof NewReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/preprocessing': {
      id: '/new/preprocessing'
      path: '/new/preprocessing'
      fullPath: '/new/preprocessing'
      preLoaderRoute: typeof NewPreprocessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/predict': {
      id: '/new/predict'
      path: '/new/predict'
      fullPath: '/new/predict'
      preLoaderRoute: typeof NewPredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/model': {
      id: '/new/model'
      path: '/new/model'
      fullPath: '/new/model'
      preLoaderRoute: typeof NewModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/metrics': {
      id: '/new/metrics'
      path: '/new/metrics'
      fullPath: '/new/metrics'
      preLoaderRoute: typeof NewMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/explain': {
      id: '/new/explain'
      path: '/new/explain'
      fullPath: '/new/explain'
      preLoaderRoute: typeof NewExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$modelId': {
      id: '/models/$modelId'
      path: '/models/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof ModelsModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  CompareRoute: CompareRoute,
  DataSourcesRoute: DataSourcesRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  ModelsModelIdRoute: ModelsModelIdRoute,
  NewExplainRoute: NewExplainRoute,
  NewMetricsRoute: NewMetricsRoute,
  NewModelRoute: NewModelRoute,
  NewPredictRoute: NewPredictRoute,
  NewPreprocessingRoute: NewPreprocessingRoute,
  NewReportRoute: NewReportRoute,
  NewSplitRoute: NewSplitRoute,
  NewTrainRoute: NewTrainRoute,
  NewUploadRoute: NewUploadRoute,
  NewVariablesRoute: NewVariablesRoute,
  NewVisualizeRoute: NewVisualizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
